# Generated by Django 4.1.4 on 2023-01-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='5678-09-22'),
            preserve_default=False,
        ),
    ]
